from .client_schema import ClientSchema
from .commande_schema import CommandeSchema
from .commune_schema import CommuneSchema
from .conditionnement_schema import ConditionnementSchema
from .departement_schema import DepartementSchema
from .detail_schema import DetailSchema
from .detail_objet_schema import DetailObjetSchema
from .enseigne_schema import EnseigneSchema
from .objet_schema import ObjetSchema
from .objet_cond_schema import ObjetCondSchema
from .poids_schema import PoidsSchema
from .role_schema import RoleSchema
from .role_utilisateur_schema import RoleUtilisateurSchema
from .utilisateur_schema import UtilisateurSchema
from .vignette_schema import VignetteSchema
