from .client_controller import *
from .commande_controller import *
from .commune_controller import *
from .conditionnement_controller import *
from .departement_controller import *
from .detail_controller import *
from .enseigne_controller import *
from .objet_controller import *
from .poids_controller import *
from .role_controller import *
from .utilisateur_controller import *
from .vignette_controller import *
